### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by JeffBusch** [Marchrius/RT73-USB-Wireless-#1]
First of all I would like to thank you for making this, I just got my Hackintosh up in running and am very surprised to see such old hardware still being supported.

The only suggestion I have is to maybe add some better directions. I had some confusion with the tool since you have to make a profile first instead of just simply connecting. 

Otherwise, great work! :+1: 
Jeff

**Comment by marchrius** [comment]
Thanks for suggestion!

Check it, is in the README file.
